config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/index'
  get 'users/my_portfolio'
  get 'users/search'
  get 'users/show'
  get 'user_cryptos/create'
  get 'user_cryptos/destroy'
  get 'cryptos/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  require 'net/http'

  has_many :user_cryptos
  has_many :users, through: :user_cryptos

  attr_accessor :can_be_added

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_lookup(ticker_symbol)
    source = "https://min-api.cryptocompare.com/data/top/exchanges/full?fsym=#{ticker_symbol}&tsym=USD"
    resp = Net::HTTP.get_response(URI.parse(source))
    data = resp.body
    looked_up_crypto = JSON.parse(data)['Data']

    return nil unless looked_up_crypto['CoinInfo']['FullName']
    new_crypto = new(ticker: looked_up_crypto['CoinInfo']['Name'], name: looked_up_crypto['CoinInfo']['FullName'])
    new_crypto.last_price = looked_up_crypto['AggregatedData']['Price']
    new_crypto
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_cryptos
  has_many :cryptos, through: :user_cryptos

 def crypto_already_added?(ticker_symbol)
    crypto = Crypto.find_by_ticker(ticker_symbol)
    return false unless crypto
    user_cryptos.where(crypto_id: crypto.id).exists?
  end

  def under_crypto_limit?
    (user_cryptos.count < 10)
  end

  def can_add_crypto?(ticker_symbol)
    under_crypto_limit? && !crypto_already_added?(ticker_symbol)
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

end

app/models/user_crypto.rb
class UserCrypto < ApplicationRecord
  belongs_to :user
  belongs_to :crypto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController

  def search
    if params[:crypto]
      @crypto ||= Crypto.new_from_lookup(params[:crypto])
    end
    if @crypto
      @crypto.can_be_added = current_user.crypto?(@crypto.ticker)

      render json: @crypto, methods: [:can_be_added]
    else
      render status: 404, json: { response: 'No crypto exists for this symbol.' }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_cryptos_controller.rb
class UserCryptosController < ApplicationController
  protect_from_forgery with: :exception, unless: -> { request.format.json? }

  def create
    crypto = Crypto.find_by_ticker(params[:crypto])
    if crypto.blank?
      crypto = Crypto.new_from_lookup(params[:crypto])
      crypto.save
    end
    @user_crypto = UserCrypto.create(user: current_user, crypto: crypto)
    flash[:success] = "Crypto #{@user_crypto.crypto.name} was successfully added"

    render json: { response: flash[:success] }, status: :ok
  end

  def destroy
    crypto = Crypto.find(params[:id])
    @user_crypto = UserCrypto.where(user_id: current_user.id, crypto_id: crypto.id).first
    @user_crypto.destroy
    flash[:notice] = "Crypto was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user_cryptos = current_user.cryptos
    @user = current_user

    respond_to do |format|
      format.html { render :my_portfolio }
      format.js { render partial: 'cryptos/list.html' }
    end
  end

  def show
    @user = User.find(params[:id])
    @user_cryptos = @user.cryptos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_cryptos_helper.rb
module UserCryptosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cryptos/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_cryptos.each do |user_cryptos| %>
      <tr>
        <td><%= user_crypto.name %></td>
        <td><%= user_crypto.ticker %></td>
        <td><%= user_crypto.last_price %></td>
        <% if @user.id == current_user.id %>
          <td><%= link_to "Delete this tracking", user_crypto_path(user_crypto), method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
<table>

app/views/cryptos/search.html.erb
<h1>Cryptos#search</h1>
<p>Find me in app/views/cryptos/search.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to the Crypto Tracker app!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render './shared/navigation' %>
    <%= react_component("Search") %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to "Crypto Tracker", root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My Portfolio", users_my_portfolio_path  %></li>
          <li><%= link_to "My Profile", edit_registration_path(current_user) %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("logout", destroy_user_session_path,
                                class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/user_cryptos/create.html.erb
<h1>UserCryptos#create</h1>
<p>Find me in app/views/user_cryptos/create.html.erb</p>

app/views/user_cryptos/destroy.html.erb
<h1>UserCryptos#destroy</h1>
<p>Find me in app/views/user_cryptos/destroy.html.erb</p>

app/views/users/my_portfolio.html.erb
<h1>Users#my_portfolio</h1>
<p>Find me in app/views/users/my_portfolio.html.erb</p>

app/views/users/search.html.erb
<h1>Users#search</h1>
<p>Find me in app/views/users/search.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>